### ISSUE TITLE
About indentation spaces and object property arrangement

### ISSUE THREAD

**Issue by oopsFrogs** [kukushi/JSONFormatter#1]
Hi, thank you for creation of this nice extension!

I wonder is it OK to add these 2 functions:

1. the user could adjust the amount of spaces for the indentation
2. the user could enable/disable whether to arrange the properties of objects alphabetically

Thanks!

**Comment by kukushi** [comment]
Thanks for using the extension.

For a background, the formatted string is generated using the system provided method with an option called `prettyPrinted`.

To implement the first feature, we have to completely rewrite the pretty printed method for JSON object. It's not that difficult but kind of overhead. I think the default format meet most needs.

The second feature is considerable and some configuration page must be added.

**Comment by kukushi** [comment]
@oopsFrogs 
The new binary with sorting have been released.
Due to the API limitation, the feature require macOS 10.13.

**Comment by oopsFrogs** [comment]
Good job! 
Thank you!
